version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd todoapp && npm run dev"
    ports:
      - "3000:3000"

  database:
    image: mysql:8.3.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mysql000ex
      MYSQL_USER: todo000db
      MYSQL_PASSWORD: todo000kun
      MYSQL_DATABASE: mysqlpass

networks:
  default:
    name: nextjs-test-network