version: '3'
services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd web && npm run dev"
    ports:
      - "3000:3000"
  java:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ../:/usr/src/web
      
  database:
    image: mysql:8.3.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mysql000ex
      MYSQL_USER: todo000db
      MYSQL_PASSWORD: todo000kun
      MYSQL_DATABASE: mysqlpass

networks:
  default:
    name: nextjs-test-network